transit_without_member = {'direction': 'OUT',
                          'end_date': '2020-07-14T10:23:07.972822',
                          'gate': 'Varco Canaletto',
                          'granted': True,
                          'id': 'EB71DC5436B54F43A91DC00110565E14',
                          'items': [],
                          'lane': 'VCL2',
                          'lane_status': 'Aperta',
                          'lane_type': 'Veicolare',
                          'members': [],
                          'operator': None,
                          'security_level': 'Livello 1',
                          'site': 'LSCT',
                          'start_date': '2020-07-14T10:23:07.967512',
                          'status': 'Autorizzato Operatore'}

transit_with_member = {'direction': 'IN',
                       'end_date': '2020-07-14T10:23:48.693648',
                       'gate': 'Varco Stagnoni',
                       'granted': True,
                       'id': 'CB69548E1CB841A88E8DE2261E149DD0',
                       'items': [{'attachments': [],
                                  'details': {'destination': '',
                                              'operator': 'marco.toracca',
                                              'reason': ''},
                                  'id': '8008D8A0E7C84520A8795C4D9CB79395',
                                  'item_type': 'Authorization'}],
                       'lane': 'VSL1_DX',
                       'lane_status': 'Aperta',
                       'lane_type': 'Veicolare',
                       'members': [{'owner': {'birthday_country': 'EG',
                                              'birthday_date': '1981-03-01T00:00:00',
                                              'company': {'company_type': 'Articolo 16',
                                                          'name': 'Quayside Service S.r.l.'},
                                              'name': 'Mohamed Adel Ali Elawo',
                                              'owner_type': 'OwnerPerson'},
                                    'permission_reference': None,
                                    'permission_type': 'Authorized by operator',
                                    'status': 'ALLOWED',
                                    'status_message': 'Authorized by operator'}],
                       'operator': 'marco.toracca',
                       'security_level': 'Livello 1',
                       'site': 'LSCT',
                       'start_date': '2020-07-14T10:23:48.688954',
                       'status': 'Autorizzato Operatore'}
