%YAML 1.1
---
LOCALHOST:
  factory: LegacyConsole
  host: 127.0.0.1
  port: 3001
CANALETTO:
  factory: LegacyConsole
  host: console005
  port: 3001
RAVANO:
  factory: LegacyConsole
  host: 127.0.0.1
  port: 3001
STAGNONI_SX:
  factory: LegacyConsole
  host: console002
  port: 3001
STAGNONI_DX:
  factory: LegacyConsole
  host: console004
  port: 3001
