
/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * urn:dvs                                                                    *
 *                                                                            *
\******************************************************************************/

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "urn:dvs"

*/

//gsoap ns1   schema namespace:	urn:dvs
//gsoap ns1   schema form:	unqualified

/* ./soap/dvs.h - Dime section
   Manually generated by Manuelito Scola.
   wsdl2h doesn't support Dime Attachment.
 */

/// "urn:dvs":DimeData is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:unsignedByte
struct ns1__DimeData
{
/// Pointer to array of unsigned char.
    unsigned char                       *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
    char                                *id                            ;
    char                                *type                          ;
    char                                *options                       ;
};

struct DimeDataArray
{
/// Pointer to array of struct ns1__DimeData*.
    struct ns1__DimeData*               *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "urn:dvs":CamerasCntxArray is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:int
struct CamerasCntxArray
{
/// Pointer to array of int.
    int                                 *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

//gsoap ns1  service method-style:	getDimePlateArray rpc
//gsoap ns1  service method-encoding:	getDimePlateArray http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	getDimePlateArray ""
int ns1__getDimePlateArray(
    int                                 cameraId,
    struct CamerasCntxArray*            camerasCntx,
    struct DimeDataArray               * ///< response parameter
);

/* End of ./soap/dvs.h - Dime section */
