/* dvsH.h
   Generated by gSOAP 2.7.9l from dime.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef dvsH_H
#define dvsH_H
#include "dvsStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_ns1__getDimePlateArray
#define SOAP_TYPE_ns1__getDimePlateArray (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDimePlateArray(struct soap*, struct ns1__getDimePlateArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDimePlateArray(struct soap*, const struct ns1__getDimePlateArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDimePlateArray(struct soap*, const struct ns1__getDimePlateArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDimePlateArray(struct soap*, const char*, int, const struct ns1__getDimePlateArray *, const char*);
SOAP_FMAC3 struct ns1__getDimePlateArray * SOAP_FMAC4 soap_get_ns1__getDimePlateArray(struct soap*, struct ns1__getDimePlateArray *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDimePlateArray * SOAP_FMAC4 soap_in_ns1__getDimePlateArray(struct soap*, const char*, struct ns1__getDimePlateArray *, const char*);

#ifndef SOAP_TYPE_ns1__getDimePlateArrayResponse
#define SOAP_TYPE_ns1__getDimePlateArrayResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getDimePlateArrayResponse(struct soap*, struct ns1__getDimePlateArrayResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getDimePlateArrayResponse(struct soap*, const struct ns1__getDimePlateArrayResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getDimePlateArrayResponse(struct soap*, const struct ns1__getDimePlateArrayResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getDimePlateArrayResponse(struct soap*, const char*, int, const struct ns1__getDimePlateArrayResponse *, const char*);
SOAP_FMAC3 struct ns1__getDimePlateArrayResponse * SOAP_FMAC4 soap_get_ns1__getDimePlateArrayResponse(struct soap*, struct ns1__getDimePlateArrayResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getDimePlateArrayResponse * SOAP_FMAC4 soap_in_ns1__getDimePlateArrayResponse(struct soap*, const char*, struct ns1__getDimePlateArrayResponse *, const char*);

#ifndef SOAP_TYPE_CamerasCntxArray
#define SOAP_TYPE_CamerasCntxArray (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_CamerasCntxArray(struct soap*, struct CamerasCntxArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_CamerasCntxArray(struct soap*, struct CamerasCntxArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_CamerasCntxArray(struct soap*, const struct CamerasCntxArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_CamerasCntxArray(struct soap*, const char*, int, const struct CamerasCntxArray *, const char*);
SOAP_FMAC3 struct CamerasCntxArray * SOAP_FMAC4 soap_get_CamerasCntxArray(struct soap*, struct CamerasCntxArray *, const char*, const char*);
SOAP_FMAC3 struct CamerasCntxArray * SOAP_FMAC4 soap_in_CamerasCntxArray(struct soap*, const char*, struct CamerasCntxArray *, const char*);

#ifndef SOAP_TYPE_DimeDataArray
#define SOAP_TYPE_DimeDataArray (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_DimeDataArray(struct soap*, struct DimeDataArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_DimeDataArray(struct soap*, struct DimeDataArray const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_DimeDataArray(struct soap*, const struct DimeDataArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_DimeDataArray(struct soap*, const char*, int, const struct DimeDataArray *, const char*);
SOAP_FMAC3 struct DimeDataArray * SOAP_FMAC4 soap_get_DimeDataArray(struct soap*, struct DimeDataArray *, const char*, const char*);
SOAP_FMAC3 struct DimeDataArray * SOAP_FMAC4 soap_in_DimeDataArray(struct soap*, const char*, struct DimeDataArray *, const char*);

#ifndef SOAP_TYPE_ns1__DimeData
#define SOAP_TYPE_ns1__DimeData (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__DimeData(struct soap*, struct ns1__DimeData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__DimeData(struct soap*, struct ns1__DimeData const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__DimeData(struct soap*, const struct ns1__DimeData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DimeData(struct soap*, const char*, int, const struct ns1__DimeData *, const char*);
SOAP_FMAC3 struct ns1__DimeData * SOAP_FMAC4 soap_get_ns1__DimeData(struct soap*, struct ns1__DimeData *, const char*, const char*);
SOAP_FMAC3 struct ns1__DimeData * SOAP_FMAC4 soap_in_ns1__DimeData(struct soap*, const char*, struct ns1__DimeData *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerToDimeDataArray
#define SOAP_TYPE_PointerToDimeDataArray (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToDimeDataArray(struct soap*, struct DimeDataArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToDimeDataArray(struct soap*, struct DimeDataArray *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToDimeDataArray(struct soap*, const char *, int, struct DimeDataArray *const*, const char *);
SOAP_FMAC3 struct DimeDataArray ** SOAP_FMAC4 soap_get_PointerToDimeDataArray(struct soap*, struct DimeDataArray **, const char*, const char*);
SOAP_FMAC3 struct DimeDataArray ** SOAP_FMAC4 soap_in_PointerToDimeDataArray(struct soap*, const char*, struct DimeDataArray **, const char*);

#ifndef SOAP_TYPE_PointerToCamerasCntxArray
#define SOAP_TYPE_PointerToCamerasCntxArray (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToCamerasCntxArray(struct soap*, struct CamerasCntxArray *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToCamerasCntxArray(struct soap*, struct CamerasCntxArray *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToCamerasCntxArray(struct soap*, const char *, int, struct CamerasCntxArray *const*, const char *);
SOAP_FMAC3 struct CamerasCntxArray ** SOAP_FMAC4 soap_get_PointerToCamerasCntxArray(struct soap*, struct CamerasCntxArray **, const char*, const char*);
SOAP_FMAC3 struct CamerasCntxArray ** SOAP_FMAC4 soap_in_PointerToCamerasCntxArray(struct soap*, const char*, struct CamerasCntxArray **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__DimeData
#define SOAP_TYPE_PointerToPointerTons1__DimeData (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__DimeData(struct soap*, struct ns1__DimeData **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__DimeData(struct soap*, struct ns1__DimeData **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__DimeData(struct soap*, const char *, int, struct ns1__DimeData **const*, const char *);
SOAP_FMAC3 struct ns1__DimeData *** SOAP_FMAC4 soap_get_PointerToPointerTons1__DimeData(struct soap*, struct ns1__DimeData ***, const char*, const char*);
SOAP_FMAC3 struct ns1__DimeData *** SOAP_FMAC4 soap_in_PointerToPointerTons1__DimeData(struct soap*, const char*, struct ns1__DimeData ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__DimeData
#define SOAP_TYPE_PointerTons1__DimeData (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DimeData(struct soap*, struct ns1__DimeData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DimeData(struct soap*, struct ns1__DimeData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DimeData(struct soap*, const char *, int, struct ns1__DimeData *const*, const char *);
SOAP_FMAC3 struct ns1__DimeData ** SOAP_FMAC4 soap_get_PointerTons1__DimeData(struct soap*, struct ns1__DimeData **, const char*, const char*);
SOAP_FMAC3 struct ns1__DimeData ** SOAP_FMAC4 soap_in_PointerTons1__DimeData(struct soap*, const char*, struct ns1__DimeData **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of dvsH.h */
