VPR-L2:
  direction: IN
  type: VEHICLE
  status: OPENED
  tags:
  - PROFILES
  device_links:
  - device: IGATE
    node: A@checkUid
  - device: VPR-BR
    node: A@openGate
    port: '2'
  - device: VPR-BR
    node: E@readerInput
    port: '2'