#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:twisted
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

Generic_error_msg_map = {
    0 : "Unknown error",
    1 : "Invalid size",
    2 : "Size is negative",
    3 : "Size is zero",
    4 : "Buffer Underflow",
    5 : "Buffer Overflow",
    6 : "Inexistent configuration parameter",
    7 : "Invalid configuration parameter value",
    8 : "Inexistent User ID",
    9 : "Operation timed out",
    10 : "Out of memory",
    11 : "Default password detected",
    12 : "WIFI module not connected",
    13 : "No space left on device",
    14 : "Not compatible with current license",
    15 : "Ethernet configuration not found",
    16 : "Failed to configure ethernet settings",
    17 : "job code validation failed",
    18 : "job code list data invalid",
    19 : "invalid job code array length",
    20 : "job code list array full",
    23 : "Send to host failed",
    24 : "License not found",
    25 : "SD card not found",
}
